### ISSUE TITLE
Example.ini uses wrong/non-functioning port

### ISSUE THREAD

**Issue by pacobyte** [tjhrulz/MessagePassingForRainmeter#5]
In the Example.ini included in MessagePassing_0.5.1.rmskin, the port number in the measure's options is as follows:
```
Port=37589
```
The plugin at this point does not allow changing ports, so the only working port, I believe, should be there so as to not confuse new users when they think the plugin isn't working:
```
Port=58932
```

**Comment by tjhrulz** [comment]
You are 100% correct, no idea why I had that in the example. I will change that to reflect the correct port and document it as being unused, thanks for catching that. 

I don't know why I never implemented multiple web servers/ports, I think I will add that to my todo list over the next few days.
